use_frameworks!

platform :ios, '9.0'

target 'MagicThought-master_Example' do
  pod 'MagicThought-master', :path => '../'

  target 'MagicThought-master_Tests' do
    inherit! :search_paths

    
  end
end
